DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS customer;


CREATE TABLE customer (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 2000, INCREMENT BY 1) PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250),
  email_id VARCHAR(50),
  address VARCHAR(250) NOT NULL
);

CREATE TABLE account(
  number INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 6000, INCREMENT BY 1) PRIMARY KEY,
  customer_id INTEGER NOT NULL,
  name VARCHAR(250) NOT NULL,
  type VARCHAR(50) NOT NULL,
  bal_date DATE,
  currency VARCHAR(10),
  avail_bal DECIMAL(12,2),
  FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 9000, INCREMENT BY 1) PRIMARY KEY,
    account_number INTEGER NOT NULL,
    value_date DATE NOT NULL,
    debit_amt DECIMAL(12,2),
    credit_amt DECIMAL(12,2),
    debit_credit VARCHAR(10) NOT NULL,
    transaction_narrative LONGVARCHAR,
    FOREIGN KEY (account_number) REFERENCES account(number)
);

INSERT INTO customer (first_name, last_name, email_id, address) VALUES
  ('Rakesh', 'Kumar', 'rakesh699@yahoo.com', 'Banksia Street Heidelberg'),
  ('Sam', 'Lee', 'samlee@yahoo.com', 'Dockland Street'),
  ('Keith', 'Lawrance', 'keith@gmail.com', '246 Brooke Street');

INSERT INTO account (customer_id, name, type, bal_date, currency, avail_bal) VALUES
  (2000, 'SGSavings726', 'Savings', DATE '2020-11-21', 'SGD', 84327.51),
  (2000, 'AUSavings933', 'Savings', DATE '2020-11-21', 'AUD', 88005.93),
  (2000, 'AUCurrent433', 'Current', DATE '2020-11-21', 'AUD', 38010.62),
  (2000, 'SGCurrent166', 'Current', DATE '2020-11-21', 'SGD', 50664.65),
  (2000, 'AUCurrent374', 'Current', DATE '2020-11-21', 'AUD', 41327.28),
  (2000, 'AUSavings938', 'Savings', DATE '2020-11-21', 'AUD', 48928.79),
  (2000, 'SGSavings842', 'Savings', DATE '2020-11-21', 'SGD', 72117.53),
  (2000, 'AUSavings253', 'Savings', DATE '2020-11-21', 'AUD', 20588.16),
  (2000, 'AUCurrent754', 'Current', DATE '2020-11-21', 'AUD', 88794.48),
  (2000, 'SGCurrent294', 'Current', DATE '2020-11-21', 'SGD', 5906.55),
  (2000, 'AUCurrent591', 'Current', DATE '2020-11-21', 'AUD', 92561.68);


INSERT INTO transactions (account_number, value_date, debit_amt, credit_amt, debit_credit) VALUES
  (6000, DATE '2016-01-01', null, 9540.98, 'Credit'),
  (6000, DATE '2016-01-01', null, 7497.82, 'Credit'),
  (6000, DATE '2016-01-01', null, 5564.79, 'Credit'),
  (6000, DATE '2016-01-01', null, 8136.18, 'Credit'),
  (6000, DATE '2016-01-01', null, 9442.46, 'Credit'),
  (6000, DATE '2016-01-01', null, 7614.45, 'Credit'),
  (6000, DATE '2016-01-01', null, 3311.55, 'Credit'),
  (6000, DATE '2016-01-01', null, 9186.09, 'Credit'),
  (6000, DATE '2016-01-01', null, 1905.86, 'Credit'),
  (6000, DATE '2016-01-01', null, 197.78, 'Credit'),
  (6000, DATE '2016-01-01', null, 8430.49, 'Credit'),
  (6000, DATE '2016-01-01', null, 8.33, 'Credit');
